# Generated by Django 5.1.6 on 2025-03-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='writer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
