# Generated by Django 5.1.7 on 2025-04-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_news_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='content_en',
            field=models.TextField(blank=True, max_length=1555, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='content_sq',
            field=models.TextField(blank=True, max_length=1555, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='title_sq',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='content_en',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='content_sq',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title_sq',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, max_length=1555, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_sq',
            field=models.TextField(blank=True, max_length=1555, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sq',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
