# Generated by Django 5.1.7 on 2025-04-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_alter_job_content_alter_job_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='content',
            field=models.TextField(blank=True, max_length=6000),
        ),
        migrations.AlterField(
            model_name='job',
            name='content_en',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='content_sq',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
    ]
