# Generated by Django 5.1.7 on 2025-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heallthApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_sq',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(default='Unknown Service', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_sq',
            field=models.CharField(default='Unknown Service', max_length=100, null=True),
        ),
    ]
